#ifndef __OCPP_FIRMWARE_STATUS_NOTIFICATION_H
#define __OCPP_FIRMWARE_STATUS_NOTIFICATION_H

#include <OcppConfig.h>
#include <OcppPrvHeader.h>

typedef enum
{
	OCPP_FIRMWARE_STATUS_DOWNLOADED,
	OCPP_FIRMWARE_STATUS_DOWNLOAD_FAILED,
	OCPP_FIRMWARE_STATUS_DOWNLOADING,
	OCPP_FIRMWARE_STATUS_IDLE,
	OCPP_FIRMWARE_STATUS_INSTALLATION_FAILED,
	OCPP_FIRMWARE_STATUS_INSTALLING,
	OCPP_FIRMWARE_STATUS_INSTALLED
} OcppFirmwareStatus;

typedef struct
{
	OcppFirmwareStatus status;
} OcppFirmwareStatusNotificationRequest;

typedef struct
{
} OcppFirmwareStatusNotificationResponse;

#endif // __OCPP_FIRMWARE_STATUS_NOTIFICATION_H