/**
 * @file OcppPrvHeader.h
 * @author Xuan Tho Do (tho.dok17@gmail.com)
 * @brief
 * @version 0.1
 * @date 2025-02-24
 *
 * @copyright Copyright (c) 2025
 *
 */

#ifndef __OCPP_TYPES_H
#define __OCPP_TYPES_H

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include <jsmn.h>
#include <OcppConfig.h>

#define OCPP_OK 0x00
#define OCPP_NOT_OK 0x01
#define OCPP_INVALID 0x02
#define OCPP_NOT_FOUND 0x03

typedef uint8_t OcppRetType;

typedef enum
{
	OCPP_MESSAGE_STATUS_ACCEPTED,
	OCPP_MESSAGE_STATUS_REJECTED,
	OCPP_MESSAGE_STATUS_FAILED,
	OCPP_MESSAGE_STATUS_FAULTED,
	OCPP_MESSAGE_STATUS_OCCUPIED,
	OCPP_MESSAGE_STATUS_UNAVAILABLE,
	OCPP_MESSAGE_STATUS_BLOCKED,
	OCPP_MESSAGE_STATUS_PENDING,
	OCPP_MESSAGE_STATUS_EXPIRED,
	OCPP_MESSAGE_STATUS_INVALID,
	OCPP_MESSAGE_STATUS_CONCURRENT_TX,
	OCPP_MESSAGE_STATUS_SCHEDULED,
	OCPP_MESSAGE_STATUS_REBOOT_REQUIRED,
	OCPP_MESSAGE_STATUS_NOT_SUPPORTED,
	OCPP_MESSAGE_STATUS_UNKNOWN_MESSAGE_ID,
	OCPP_MESSAGE_STATUS_UNKNOWN_VENDOR_ID,
	OCPP_MESSAGE_STATUS_VERSION_MISMATCH,
	OCPP_MESSAGE_STATUS_NOT_IMPLEMENTED,
	OCPP_MESSAGE_STATUS_UNLOCKED,
	OCPP_MESSAGE_STATUS_UNLOCK_FAILED,
	OCPP_MESSAGE_STATUS_AVAILABLE,

	OCPP_MESSAGE_STATUS_MAX
} OcppMessageStatus;

typedef enum
{
	OCPP_CHARGING_RATE_UNIT_A,
	OCPP_CHARGING_RATE_UNIT_W,

	OCPP_CHARGING_RATE_UNIT_MAX
} OcppChargingRateUnitType;

typedef enum
{
	OCPP_CHARGING_PROFILE_PP_CP_MAX,
	OCPP_CHARGING_PROFILE_PP_TX_DEFAULT_MAX,
	OCPP_CHARGING_PROFILE_PP_TX_PROFILE,

	OCPP_CHARGING_PROFILE_PP_MAX
} OcppChargingProfilePurpose;

typedef enum
{
	OCPP_CHARGING_PROFILE_KIND_ABSOLUTE,
	OCPP_CHARGING_PROFILE_KIND_RECURRING,
	OCPP_CHARGING_PROFILE_KIND_RELATIVE,

	OCPP_CHARGING_PROFILE_KIND_MAX
} OcppChargingProfileKind;

typedef enum
{
	OCPP_RECURRENCY_KIND_DAILY,
	OCPP_RECURRENCY_KIND_WEEKLY,

	OCPP_RECURRENCY_KIND_MAX
} OcppRecurrencyKind;

typedef enum
{
	OCPP_CP_STATUS_AVAILABLE = 1,
	OCPP_CP_STATUS_PREPARING,
	OCPP_CP_STATUS_CHARGING,
	OCPP_CP_STATUS_SUSPENDED_EV,
	OCPP_CP_STATUS_SUSPENDED_EVSE,
	OCPP_CP_STATUS_FINISHING,
	OCPP_CP_STATUS_RESERVED,
	OCPP_CP_STATUS_UNAVAILABLE,
	OCPP_CP_STATUS_FAULTED,
	OCPP_CP_STATUS_EMERGENCY,

	OCPP_CP_STATUS_MAX
} OcppChargePointStatus;

typedef enum
{
	OCPP_CP_ERR_CONN_LOCK_FAIL,
	OCPP_CP_ERR_EV_COMM,
	OCPP_CP_ERR_GND_FAILURE,
	OCPP_CP_ERR_HIGH_TEMPERATURE,
	OCPP_CP_ERR_INTERNAL_ERROR,
	OCPP_CP_ERR_LOCAL_LIST_CONFLICT,
	OCPP_CP_ERR_NO_ERROR,
	OCPP_CP_ERR_OTHER_ERROR,
	OCPP_CP_ERR_OVER_CURR_FAL,
	OCPP_CP_ERR_POWER_METER_FAIL,
	OCPP_CP_ERR_POWER_SWI_FAIL,
	OCPP_CP_ERR_READER_FAIL,
	OCPP_CP_ERR_RESET_FAIL,
	OCPP_CP_ERR_UNDER_VOLTAGE,
	OCPP_CP_ERR_OVER_VOLTAGE,
	OCPP_CP_ERR_WEAK_SIGNAL,

	OCPP_CP_ERR_MAX
} OcppChargePointErrorCode;

typedef enum
{
	OCPP_SAMPLED_VALUE_CONTEXT_INTERRUPTION_BEGIN,
	OCPP_SAMPLED_VALUE_CONTEXT_INTERRUPTION_END,
	OCPP_SAMPLED_VALUE_CONTEXT_SAMPLE_CLOCK,
	OCPP_SAMPLED_VALUE_CONTEXT_SAMPLE_PERIOD,
	OCPP_SAMPLED_VALUE_CONTEXT_TRANSACTION_BEGIN,
	OCPP_SAMPLED_VALUE_CONTEXT_TRANSACTION_END,
	OCPP_SAMPLED_VALUE_CONTEXT_TRIGGER,
	OCPP_SAMPLED_VALUE_CONTEXT_OTHER,

	OCPP_SAMPLED_VALUE_CONTEXT_MAX
} OcppSampledValueContext;

typedef enum
{
	OCPP_SAMPLED_VALUE_FORMAT_RAW,
	OCPP_SAMPLED_VALUE_FORMAT_SIGNED_DATA,

	OCPP_SAMPLED_VALUE_FORMAT_MAX
} OcppSampledValueFormat;

typedef enum
{
	OCPP_SAMPLED_VALUE_MEASURAND_EN_ACT_EX_REG,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_ACT_IM_REG,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_REACT_EX_REG,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_REACT_IM_REG,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_ACT_EX_INT,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_ACT_IM_INT,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_REACT_EX_INT,
	OCPP_SAMPLED_VALUE_MEASURAND_EN_REACT_IM_INT,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_ACT_EX,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_ACT_IM,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_OFFER,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_REACT_EX,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_REACT_IM,
	OCPP_SAMPLED_VALUE_MEASURAND_PO_FACTOR,
	OCPP_SAMPLED_VALUE_MEASURAND_CURR_IM,
	OCPP_SAMPLED_VALUE_MEASURAND_CURR_EX,
	OCPP_SAMPLED_VALUE_MEASURAND_CURR_OFFER,
	OCPP_SAMPLED_VALUE_MEASURAND_VOLT,
	OCPP_SAMPLED_VALUE_MEASURAND_FREQ,
	OCPP_SAMPLED_VALUE_MEASURAND_TEMPERATURE,
	OCPP_SAMPLED_VALUE_MEASURAND_SOC,
	OCPP_SAMPLED_VALUE_MEASURAND_RPM,

	OCPP_SAMPLED_VALUE_MEASURAND_MAX

} OcppSampledValueMeasurand;

typedef enum
{
	OCPP_SAMPLED_VALUE_PHASE_L1,
	OCPP_SAMPLED_VALUE_PHASE_L2,
	OCPP_SAMPLED_VALUE_PHASE_L3,
	OCPP_SAMPLED_VALUE_PHASE_N,
	OCPP_SAMPLED_VALUE_PHASE_L1_N,
	OCPP_SAMPLED_VALUE_PHASE_L2_N,
	OCPP_SAMPLED_VALUE_PHASE_L3_N,
	OCPP_SAMPLED_VALUE_PHASE_L1_L2,
	OCPP_SAMPLED_VALUE_PHASE_L2_L3,
	OCPP_SAMPLED_VALUE_PHASE_L3_L1,

	OCPP_SAMPLED_VALUE_PHASE_MAX
} OcppSampledValuePhase;

typedef enum
{
	OCPP_SAMPLED_VALUE_LOC_CABLE,
	OCPP_SAMPLED_VALUE_LOC_EV,
	OCPP_SAMPLED_VALUE_LOC_INLET,
	OCPP_SAMPLED_VALUE_LOC_OUTLET,
	OCPP_SAMPLED_VALUE_LOC_BODY,

	OCPP_SAMPLED_VALUE_LOC_MAX
} OcppSampledValueLocation;

typedef enum
{
	OCPP_SAMPLED_VALUE_UNIT_WH,
	OCPP_SAMPLED_VALUE_UNIT_KWH,
	OCPP_SAMPLED_VALUE_UNIT_VARH,
	OCPP_SAMPLED_VALUE_UNIT_KVARH,
	OCPP_SAMPLED_VALUE_UNIT_W,
	OCPP_SAMPLED_VALUE_UNIT_KW,
	OCPP_SAMPLED_VALUE_UNIT_VA,
	OCPP_SAMPLED_VALUE_UNIT_KVA,
	OCPP_SAMPLED_VALUE_UNIT_VAR,
	OCPP_SAMPLED_VALUE_UNIT_KVAR,
	OCPP_SAMPLED_VALUE_UNIT_A,
	OCPP_SAMPLED_VALUE_UNIT_V,
	OCPP_SAMPLED_VALUE_UNIT_K,
	OCPP_SAMPLED_VALUE_UNIT_CELCIUS,
	OCPP_SAMPLED_VALUE_UNIT_CELSIUS,
	OCPP_SAMPLED_VALUE_UNIT_FAHRENHEIT,
	OCPP_SAMPLED_VALUE_UNIT_PERCENT,

	OCPP_SAMPLED_VALUE_UNIT_MAX
} OcppSampledValueUnit;

typedef enum
{
	OCPP_UPDATE_TYPE_DIFFERENTIAL,
	OCPP_UPDATE_TYPE_FULL,

	OCPP_UPDATE_TYPE_MAX
} OcppUpdateType;

typedef enum
{
	OCPP_AVAILABILITY_TYPE_INOPERATIVE,
	OCPP_AVAILABILITY_TYPE_OPERATIVE,

	OCPP_AVAILABILITY_TYPE_MAX
} OcppAvailabilityType;

typedef enum
{
	OCPP_DIAGNOSTIC_STATUS_IDLE,
	OCPP_DIAGNOSTIC_STATUS_UPLOADED,
	OCPP_DIAGNOSTIC_STATUS_UPLOAD_FAILED,
	OCPP_DIAGNOSTIC_STATUS_UPLOADING,

	OCPP_DIAGNOSTIC_STATUS_MAX
} OcppDiagnosticsStatus;

typedef enum
{
	OCPP_FIRMWARE_STATUS_DOWNLOADED,
	OCPP_FIRMWARE_STATUS_DOWNLOAD_FAILED,
	OCPP_FIRMWARE_STATUS_DOWNLOADING,
	OCPP_FIRMWARE_STATUS_IDLE,
	OCPP_FIRMWARE_STATUS_INSTALLATION_FAILED,
	OCPP_FIRMWARE_STATUS_INSTALLING,
	OCPP_FIRMWARE_STATUS_INSTALLED,

	OCPP_FIRMWARE_STATUS_MAX
} OcppFirmwareStatus;

typedef enum
{
	OCPP_REASON_EMG_STOP,
	OCPP_REASON_EV_DISCONNECTED,
	OCPP_REASON_HARD_RESET,
	OCPP_REASON_LOCAL,
	OCPP_REASON_OTHER,
	OCPP_REASON_POWER_LOSS,
	OCPP_REASON_REBOOT,
	OCPP_REASON_REMOTE,
	OCPP_REASON_SOFT_RESET,
	OCPP_REASON_UNLOCK_COMMAND,
	OCPP_REASON_DEAUTHORIZED,

	OCPP_REASON_MAX
} OcppReason;

typedef enum
{
	OCPP_MESSAGE_TYPE_CALL = 2,
	OCPP_MESSAGE_TYPE_CALL_RESULT = 3,
	OCPP_MESSAGE_TYPE_CALL_ERROR = 4
} OcppMessageTypeId;

typedef enum
{
	OCPP_ACTION_AUTHORIZE,
	OCPP_ACTION_BOOT_NOTIFICATION,
	OCPP_ACTION_CANCEL_RESERVATION,
	OCPP_ACTION_CHANGE_AVAILABILITY,
	OCPP_ACTION_CHANGE_CONFIGURATION,
	OCPP_ACTION_CLEAR_CACHE,
	OCPP_ACTION_CLEAR_CHARGING_PROFILE,
	OCPP_ACTION_DATA_TRANSFER,
	OCPP_ACTION_DIAGNOSTIC_STATUS_NOTIFICATION,
	OCPP_ACTION_FIRMWARE_STATUS_NOTIFICATION,
	OCPP_ACTION_GET_COMPOSITE_SCHEDULE,
	OCPP_ACTION_GET_CONFIGURATION,
	OCPP_ACTION_GET_DIAGNOSTIC,
	OCPP_ACTION_GET_LOCAL_LIST_VERSION,
	OCPP_ACTION_HEARTBEAT,
	OCPP_ACTION_METER_VALUE,
	OCPP_ACTION_REMOTE_START_TRANSACTION,
	OCPP_ACTION_REMOTE_STOP_TRANSACTION,
	OCPP_ACTION_RESERVE_NOW,
	OCPP_ACTION_RESET,
	OCPP_ACTION_SEND_LOCAL_LIST,
	OCPP_ACTION_SET_CHARGING_PROFILE,
	OCPP_ACTION_START_TRANSACTION,
	OCPP_ACTION_STATUS_NOTIFICATION,
	OCPP_ACTION_STOP_TRANSACTION,
	OCPP_ACTION_TRIGGER_MESSAGE,
	OCPP_ACTION_UNLOCK_CONNECTOR,
	OCPP_ACTION_UPDATE_FIRMWARE,

	OCPP_ACTION_MAX
} OcppActionId;

typedef enum
{
	OCPP_ERROR_CODE_NOT_IMPLEMENTED,
	OCPP_ERROR_CODE_NOT_SUPPORTED,
	OCPP_ERROR_CODE_INTERNAL_ERROR,
	OCPP_ERROR_CODE_MESSAGE_TYPE_NOT_SUPPORTED,
	OCPP_ERROR_CODE_PROTOCOL_ERROR,
	OCPP_ERROR_CODE_SECURITY_ERROR,
	OCPP_ERROR_CODE_PROPERTY_CONSTRAIN_VIOLATION,
	OCPP_ERROR_CODE_OCCURRENCE_CONSTRAIN_VIOLATION,
	OCPP_ERROR_CODE_TYPE_CONSTRAIN_VIOLATION,
	OCPP_ERROR_CODE_GENERIC_ERROR,
	OCPP_ERROR_CODE_FORMAT_VIOLATION,
	OCPP_ERROR_CODE_FORMATION_VIOLATION,

	OCPP_ERROR_CODE_MAX
} OcppErrorCode;

typedef enum
{
	OCPP_RESET_TYPE_HARD,
	OCPP_RESET_TYPE_SOFT,

	OCPP_RESET_TYPE_MAX
} OcppResetType;

typedef enum
{
	OCPP_TRIGGER_MESSAGE_BOOT_NOTIFICATION,
	OCPP_TRIGGER_MESSAGE_DIAGNOSTIC_NOTIFICATION,
	OCPP_TRIGGER_MESSAGE_FIRMWARE_STATUS_NOTIFICATION,
	OCPP_TRIGGER_MESSAGE_HEARTBEAT,
	OCPP_TRIGGER_MESSAGE_METER_VALUE,
	OCPP_TRIGGER_MESSAGE_STATUS_NOTIFICATION,

	OCPP_TRIGGER_MESSAGE_MAX
} OcppMessageTrigger;

typedef char OcppCiString20Type[20];
typedef char OcppCiString25Type[25];
typedef char OcppCiString50Type[50];
typedef char OcppCiString255Type[255];
typedef char OcppCiString500Type[500];
typedef struct
{
	uint16_t year;
	uint8_t month;
	uint8_t day;
	uint8_t hour;
	uint8_t minute;
	uint8_t second;
	uint8_t millisecond;
	int8_t timeZone;
} OcppDateTime;

typedef OcppCiString20Type OcppIdToken;
typedef struct
{
	OcppDateTime expiryDate;
	OcppIdToken parentIdTag;
	OcppMessageStatus status;
} OcppIdTagInfo;

typedef OcppMessageStatus OcppAvailabilityStatus;
typedef OcppMessageStatus OcppRegistrationStatus;
typedef OcppMessageStatus OcppCancelReservationStatus;
typedef OcppMessageStatus OcppAvailabilityStatus;
typedef OcppMessageStatus OcppConfigurationStatus;
typedef OcppMessageStatus OcppClearCacheStatus;
typedef OcppMessageStatus OcppClearChargingProfileStatus;
typedef OcppMessageStatus OcppDataTransferStatus;
typedef OcppMessageStatus OcppGetCompositeScheduleStatus;
typedef OcppMessageStatus OcppRemoteStartStopStatus;
typedef OcppMessageStatus OcppReservationStatus;
typedef OcppMessageStatus OcppResetStatus;
typedef OcppMessageStatus OcppUpdateStatus;
typedef OcppMessageStatus OcppChargingProfileStatus;
typedef OcppMessageStatus OcppTriggerMessageStatus;
typedef OcppMessageStatus OcppUnlockStatus;

typedef char OcppUuid[OCPP_UUID_LENGTH];

typedef struct
{
	OcppIdToken idTag;
	OcppIdTagInfo idTagInfo;
} OcppAuthorizationData;

typedef struct
{
	OcppCiString50Type key;
	bool readonly;
	OcppCiString500Type value;
} OcppKeyValue;

typedef struct
{
	char value[OCPP_METER_VALUE_SAMPLED_VALUE_VALUE_MAX_LENGTH];
	OcppSampledValueContext context;
	OcppSampledValueFormat format;
	OcppSampledValueMeasurand measurand;
	OcppSampledValuePhase phase;
	OcppSampledValueLocation location;
	OcppSampledValueUnit unit;
} OcppSampledValue;

typedef struct
{
	OcppDateTime timestamp;
	OcppSampledValue sampledValue[OCPP_METER_VALUE_SAMPLED_VALUE_ARRAY_MAX_LENGTH];
	int noSampledValue;
} OcppMeterValue;

typedef struct
{
	int startPeriod;
	int limit;
	int numberPhases;
} OcppChargingSchedulePeriod;

typedef struct
{
	int duration;
	OcppDateTime startSchedule;
	OcppChargingRateUnitType chargingRateUnit;
	OcppChargingSchedulePeriod chargingSchedulePeriod[OCPP_CHARGE_SCHEDULE_CHARGING_SCH_PERIOD_MAX];
	int noChargingSchedulePeriod;
	int minChargingRate;
} OcppChargingSchedule;

typedef struct
{
	int chargingProfileId;
	int transactionId;
	int stackLevel;
	OcppDateTime validFrom;
	OcppDateTime validTo;
	OcppChargingProfilePurpose chargingProfilePurpose;
	OcppChargingProfileKind chargingProfileKind;
	OcppRecurrencyKind recurrencyKind;
	OcppChargingSchedule chargingSchedule;
} OcppChargingProfile;

#endif // __OCPP_TYPES_H